spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/identifiers?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: 123456
  cache:
    redis:
      time-to-live: 600000

mybatis:
  type-aliases-package: com.example.springwebredis.web.model
  mapper-locations: classpath:com/example/springwebredis/web/mapper/*Mapper.xml
  configuration:
#    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    cache-enabled: true
