management:
  endpoints:
    web:
      exposure:
        include: "*"

foo:
  datasource:
    url: jdbc:h2:mem:foo
    username: sa
    password:
bar:
  datasource:
    url: jdbc:h2:mem:bar
    username: sa
    password: